name=ExpFilter
version=1.0.0
author=Ir0nc0wb0y
maintainer=Ir0nc0wb0y
sentence=Simple templated exponential smoothing filter.
paragraph=Reusable exponential moving average filter supporting any numeric type.
category=Data Processing
url=https://github.com/Ir0nC0wb0y/Filter_Library.git
architectures=*